# Generated by Django 4.2 on 2026-08-21 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0002_tea_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tea',
            name='category',
            field=models.CharField(choices=[('masala', 'Masala & Spiced'), ('green', 'Green & Fresh'), ('herbal', 'Herbal & Floral'), ('black', 'Strong & Black')], default='masala', max_length=20),
        ),
    ]
