# Generated by Django 5.2.17 on 2026-08-25 18:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chai', '0003_tea_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tea',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
